CC = clang
CFLAGS = -Wall -Wextra -Werror -Wpedantic

all: integrate

integrate: integrate.o functions.o mathlib.o
	$(CC) -o integrate integrate.o functions.o mathlib.o
	
integrate.o: integrate.c
	$(CC) $(CFLAGS) -c integrate.c

functions.o: functions.c
	$(CC) $(CFLAGS) -c functions.c

mathlib.o: mathlib.c
	$(CC) $(CFLAGS) -c mathlib.c

clean:
	rm -f integrate *.o

format:
	clang-format -i -style=file *.[c,h]

